# Based on the "trust" template v0.1.2
# https://github.com/japaric/trust/tree/v0.1.2

dist: trusty
language: rust
rust: nightly-2018-12-19
services: docker
sudo: required

env:
  global:
    - CRATE_NAME=artifact

matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-gnu
    - env: TARGET=x86_64-apple-darwin
      os: osx
    # - env: TARGET=x86_64-pc-windows-gnu
    #   os: windows
    # - env: TARGET=x86_64-pc-windows-msvc
    #   os: windows

before_install:
  - set -e
  # - export BTOOL='sudo env "PATH=$PATH" cross'
  - export BTOOL=cargo
  - export RELEASE_NAME="$CRATE_NAME-$TRAVIS_TAG-$TARGET"
  - echo TARGET=$TARGET
  - export RTARGET=nightly-2018-12-19-$TARGET
  - echo RTARGET=$RTARGET
  - echo RELEASE_NAME=$RELEASE_NAME
  - export RUST_BACKTRACE=1

install:
  - rustup target add $RTARGET
  - rustup target add wasm32-unknown-unknown
  - rustup self update
  - rustup show

    # debug becuase they are very slow
  - cargo install cargo-web --force --debug
  - cargo install mdbook --force --debug
  - source ~/.cargo/env || true

script:
    - bash ci/script.sh

after_script: set +e

before_deploy:
  - sh ci/before_deploy.sh

deploy:
  api_key:
    secure: mup1wr3gAlbMJARUpcE/573zjVHWIM3iwdzcH/6hW8RqcSJNuNz964AF/xQcIrCC4y8aZOboOPZLtc2Spo5oDk0NmygOaSbQXlJwJWdbWJ15GXTi0FMzsC83waBCO7xwKXkewqCc+NCsuPbkVoJugcETcgx0ymDaeFP6i3NAs43uIjxdHeVv58BshAwZszp0DuQZWg73Vy4diPSWyVvDYQYtYRVs6Xl9/xlIGL1peORZnk/dFhfI0zvxajNqoOyhwIJzp8nUuwVBxomsBtJ5sKa4T7FAN5HGe4EnMFfnSwAYl5ffjVd4okyMrmDAdl6nveSgeGxcT8kmMpjrLTAEjd7JBw1Pa5mIY+7YduR/XrruLwLCCix0UJpjETppXG18J0gla+znqRCMxSil2GQ18d7TW7c8uetBSDjTn+tLHqSigfXtKExLYnkFOxEzISkHYw0jTHwAadtcxJLaKMsG2MOOFc7eeHuevIftJz7r2ONkORo9s9AX64hGEZVea9+qm27y+QJ6Cor8CZa+8cmdm/NsiWAcbXDg1YpG2MSAHeF/tmqfeVSJiloKJnCnMDE1Rcg2ZmHLd12qUfuF+CrbqpVdunjfFUN6bq0igjN1BfocIsl1285KCiOBZr5p91Wg5Mn87YNR3hihRkU5s32TTH2gETHP+Y24jXtLZQZxdPw=
  file_glob: true
  file: $RELEASE_NAME.*
  on:
    # condition: $TRAVIS_RUST_VERSION = stable
    tags: true
  provider: releases
  skip_cleanup: true

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    # release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master

notifications:
  email:
    on_success: never
